### ISSUE TITLE
AppModule里MainApp的注入是否多余

### ISSUE THREAD

**Issue by narakai** [Chaoba/HearthstoneCards#2]
AppModule里Provides的MainApp的注入是否多余，其他地方貌似没有注入此类。

**Comment by Chaoba** [comment]
@narakai 目前来讲是这样的，但是如果以后扩展或者是在别的大一点的项目里需要MainApp的可能性还是很高的，所以在这里先加上。

**Comment by narakai** [comment]
好的 谢谢解答
